version: "0.1"
services:
  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=kc-user
      - POSTGRES_PASSWORD=kc-password
      - POSTGRES_DB=kc
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - net_keycloak
  keycloak:
    container_name: keycloak_server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "127.0.0.1:8081:8080"
      - "127.0.0.1:8787:8787"
    networks:
      - net_keycloak
    depends_on:
      - keycloak_postgres

networks:
  net_keycloak:
    name: net_keycloak
    driver: bridge
